databases:
  - name: arnauruizdb
    plan: free
    databaseName: arnauruizdb
    user: arnauruizdb_user

services:
  - type: web
    plan: free
    name: arnauruiz
    region: frankfurt
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn arnauruiz.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arnauruizdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
